### ISSUE TITLE
Tune stops after one trial

### ISSUE THREAD

**Issue by athenawisdoms** [ray-project/ray_lightning#29]
Hello again,

I'm using Lightning's `EarlyStopping` callback and `TuneReportCallback` callback in Lightning's `Trainer`. I notice that despite having used `tune.choice` in the `config` object passed into `tune.run()`, the tuning loop always stop after the first trial has stopped.

Here is the log messages at the end of the tuning loop

```
Number of trials: 1/1 (1 TERMINATED)

+-------------------+------------+-------+-----------+-----------------+--------+------------------+----------+
| Trial name        | status     | loc   |   dropout |   learning_rate |   iter |   total time (s) |     loss |
|-------------------+------------+-------+-----------+-----------------+--------+------------------+----------|
| train_01563_00000 | TERMINATED |       |       0.6 |           0.005 |     54 |          1934.75 | 0.104323 |
+-------------------+------------+-------+-----------+-----------------+--------+------------------+----------+

2021-04-04 19:57:30,648 INFO tune.py:450 -- Total run time: 1937.71 seconds (1937.64 seconds for the tuning loop).
```

My code goes like

```py
trainer = Trainer(
    max_epochs=10,
    gpus=2,
    accelerator="ddp",
    plugins=[
        RayPlugin(num_workers=2, use_gpu=True),
    ],
    callbacks=[
        EarlyStopping(
            monitor="val_loss",
            patience=30
        ), 
        TuneReportCallback({"loss": "val_loss"}, on="validation_end")
    ],
)
```
```py
config = {
    "dropout": tune.choice([0.4, 0.6]),
    "learning_rate": tune.choice([5e-5, 5e-4, 5e-3]),
}

analysis = tune.run(
    train,
    metric="loss",
    mode="min",
    config=config,
)
```

Will love to know any ideas on why it can't do more than 1 trial... Thank you!

**Comment by amogkam** [comment]
Hey @athenawisdoms, `tune.run` also takes in a `num_samples` args which specifies how many trials to run, where each trial samples from the provided search space. The default value for this is 1, so only 1 trial is being run.

Sounds to me that you want to not sample from the search space, but actually search through all combinations of the search space. In that case, you should use `tune.grid_search` instead of `tune.choice`.

You can find more info here https://docs.ray.io/en/master/tune/user-guide.html#search-space-grid-random

**Comment by athenawisdoms** [comment]
Thank you, solved!
